version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
  labels:
  - dependencies
- package-ecosystem: gomod
  directory: /hack/generators/
  schedule:
    interval: daily
  labels:
  - dependencies
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  labels:
  - github_actions
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
  labels:
  - docker
