# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.33.0
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.32.3
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.31.6
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.30.13
