run:
  timeout: 5m
linters:
  enable:
  - asciicheck
  - bodyclose
  - copyloopvar
  - dogsled
  - durationcheck
  - errcheck
  - errorlint
  - exhaustive
  - forbidigo
  - gci
  - gocritic
  - gofmt
  - goimports
  - gomodguard
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - misspell
  - nakedret
  - nilerr
  - nolintlint
  - predeclared
  - revive
  - staticcheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - wastedassign
  - loggercheck
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/kong/kubernetes-configuration)
      - prefix(github.com/kong/gateway-operator)
  govet:
    enable-all: true # To have checks like e.g. unusedwrite.
    disable:
      - fieldalignment
      - shadow
  importas:
    no-unaliased: true
    alias:
      - pkg: k8s.io/api/([a-z])/(v[\w\d]+)
        alias: ${1}${2}

      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
      - pkg: sigs.k8s.io/gateway-api/apis/(v[\w\d]+)
        alias: gateway${1}

      - pkg: sigs.k8s.io/controller-runtime/pkg/log
        alias: ctrllog

      - pkg: github.com/kong/gateway-operator/internal/types
        alias: gwtypes
      - pkg: github.com/kong/kubernetes-configuration/api/configuration/([\w\d]+)
        alias: configuration${1}

      - pkg: github.com/Kong/sdk-konnect-go/models/components
        alias: sdkkonnectcomp
      - pkg: github.com/Kong/sdk-konnect-go/models/operations
        alias: sdkkonnectops
      - pkg: github.com/Kong/sdk-konnect-go/models/sdkerrors
        alias: sdkkonnecterrs
      - pkg: github.com/kong/gateway-operator/controller/konnect/ops/sdk
        alias: sdkops
      - pkg: github.com/kong/gateway-operator/controller/konnect/ops/sdk/mocks
        alias: sdkmocks

  revive:
    rules:
      - name: errorf
        severity: warning
        disabled: false
      - name: error-strings
        severity: warning
        disabled: false
      - name: error-naming
        severity: warning
        disabled: false
      - name: duplicated-imports
        severity: warning
        disabled: false
      - name: empty-block
        severity: warning
        disabled: false
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          # TODO: enable this when ready to refactor exported types that stutter at call site.
          - "disableStutteringCheck"
      - name: context-as-argument
        # TODO: re-add this rule after https://github.com/golangci/golangci-lint/issues/3280
        # is resolved and released.
        # arguments:
        #   - "allowTypesBefore": "*testing.T"
        disabled: true
  exhaustive:
    default-signifies-exhaustive: true
  gomodguard:
    blocked:
      modules:
      - golang.org/x/exp:
         recommendations:
          - maps
          - slices
          - github.com/samber/lo
      - github.com/pkg/errors:
          recommendations:
          - fmt
          - errors
      - github.com/sirupsen/logrus:
          recommendations:
          - sigs.k8s.io/controller-runtime/pkg/log
          - go.uber.org/zap/zapcore
  forbidigo:
    forbid:
      - p: ^.*Dataplane.*$
        msg: "Please use camel case 'DataPlane' instead of 'Dataplane'"
      - p: ^.*Controlplane.*$
        msg: "Please use camel case 'ControlPlane' instead of 'Controlplane'"
issues:
  max-same-issues: 0
  fix: true
  exclude-dirs:
    - pkg/clientset
    - config/
  include:
    - EXC0012
  exclude-rules:
    # Exclude checking exported comments in internal/ which cannot be used from outside.
    - path: internal/
      linters:
        - revive
      text: "exported: exported"
    # Test cases are self-explanatory, thus no need a docstring.
    - path: test/integration
      linters:
        - revive
      text: "exported: exported"
    - path: test/e2e
      linters:
        - revive
      text: "exported: exported"
    # Generated mock SDKs does not need comments on generated methods.
    - path: controller/konnect/ops/.*_mock\.go
      linters:
        - revive
      text: "exported: exported"
    # Methods imported from the SDK do not use the camel case naming convention for DP and we have no control over it.
    - linters:
        - forbidigo
      text: 'use of `.*(Create|Delete)Dataplane.+` forbidden because "Please use camel case'
