quiet: False
disable-version-string: True
with-expecter: True

filename: "zz_generated.{{ trimSuffix .InterfaceFile \".go\" | base | lower }}_mock.go"
dir: "{{ .InterfaceDir }}/mocks"
mockname: "Mock{{ .InterfaceName }}"
outpkg: "mocks"

packages:
  github.com/kong/gateway-operator/controller/konnect/ops/sdk:
    interfaces:
      ControlPlaneSDK:
      ControlPlaneGroupSDK:
      ServicesSDK:
      RoutesSDK:
      ConsumersSDK:
      ConsumerGroupSDK:
      PluginSDK:
      UpstreamsSDK:
      TargetsSDK:
      VaultSDK:
      MeSDK:
      KongCredentialAPIKeySDK:
      KongCredentialACLSDK:
      KongCredentialBasicAuthSDK:
      KongCredentialJWTSDK:
      KongCredentialHMACSDK:
      CACertificatesSDK:
      CertificatesSDK:
      KeysSDK:
      KeySetsSDK:
      SNIsSDK:
      DataPlaneClientCertificatesSDK:
