quiet: False
inpackage: True
disable-version-string: True
with-expecter: True

filename: "{{ trimSuffix .InterfaceFile \".go\" | base | lower }}_mock.go"
dir: "{{ .InterfaceDir }}"
mockname: "Mock{{ .InterfaceName }}"
outpkg: "{{ .PackageName }}"

packages:
  github.com/kong/gateway-operator/controller/konnect/ops:
    interfaces:
      ControlPlaneSDK:
      ServicesSDK:
      RoutesSDK:
      ConsumersSDK:
      ConsumerGroupSDK:
      PluginSDK:
      UpstreamsSDK:
      TargetsSDK:
      VaultSDK:
      MeSDK:
      KongCredentialBasicAuthSDK:
      CACertificatesSDK:
