# renovate: datasource=github-releases depName=kubernetes/code-generator
code-generator: "0.29.1"
# renovate: datasource=github-releases depName=kubernetes-sigs/controller-tools
controller-tools: "0.14.0"
# renovate: datasource=github-releases depName=kubernetes-sigs/kustomize
kustomize: "5.3.0"
# renovate: datasource=github-releases depName=golangci/golangci-lint
golangci-lint: "1.57.2"
# renovate: datasource=github-releases depName=GoogleContainerTools/skaffold
skaffold: "2.11.1"
# renovate: datasource=github-releases depName=go-delve/delve
dlv: "1.22.1"
# renovate: datasource=github-releases depName=mikefarah/yq
yq: "4.43.1"
# renovate: datasource=github-releases depName=gotestyourself/gotestsum
gotestsum: "1.11.0"
# renovate: datasource=github-releases depName=elastic/crd-ref-docs
crd-ref-docs: "0.0.12"
