# renovate: datasource=github-tags depName=kubernetes/code-generator
code-generator: "0.33.0"
# renovate: datasource=github-releases depName=kubernetes-sigs/controller-tools
controller-tools: "0.18.0"
# renovate: datasource=github-releases depName=kubernetes-sigs/kustomize
kustomize: "5.6.0"
# renovate: datasource=github-releases depName=golangci/golangci-lint
golangci-lint: "2.1.6"
# renovate: datasource=github-releases depName=GoogleContainerTools/skaffold
skaffold: "2.16.0"
# renovate: datasource=github-releases depName=go-delve/delve
dlv: "1.24.2"
# renovate: datasource=github-releases depName=gotestyourself/gotestsum
gotestsum: "1.12.2"
# renovate: datasource=github-releases depName=elastic/crd-ref-docs
crd-ref-docs: "0.1.0"
# renovate: datasource=github-releases depName=vektra/mockery
mockery: "3.4.0"
# renovate: datasource=github-releases depName=kubernetes-sigs/controller-runtime
setup-envtest: "0.21.0"
# renovate: datasource=github-releases depName=rhysd/actionlint
actionlint: "1.7.7"
# renovate: datasource=github-releases depName=koalaman/shellcheck
shellcheck: "0.10.0"
# NOTE: This does not work and requires further investigation.
# Perhaps it's possible to use a git url but https://go.googlesource.com/vuln/
# does not seem to provide one.
#
#  WARN: Custom registries are not allowed for this datasource and will be ignored (repository=local)
#        "datasource": "git-tags",
#        "registryUrls": ["https://go.googlesource.com/"],
#        "defaultRegistryUrls": null,
#        "additionalRegistryUrls": undefined
#  WARN: Attempting to use non-git url for git operations (repository=local)
#        "url": "vuln"
#
# renovate: datasource=git-tags depName=vuln registryUrl=https://go.googlesource.com
govulncheck: "1.1.4"
# renovate: datasource=github-releases depName=jlandowner/helm-chartsnap
chartsnap: "0.5.0"
# renovate: datasource=github-releases depName=stackrox/kube-linter
kube-linter: "0.7.3"
# renovate: datasource=github-releases depName=telepresenceio/telepresence
telepresence: "2.22.6"
