# renovate: datasource=github-tags depName=kubernetes/code-generator
code-generator: "0.32.1"
# renovate: datasource=github-releases depName=kubernetes-sigs/controller-tools
controller-tools: "0.17.1"
# renovate: datasource=github-releases depName=kubernetes-sigs/kustomize
kustomize: "5.6.0"
# renovate: datasource=github-releases depName=golangci/golangci-lint
golangci-lint: "1.63.4"
# renovate: datasource=github-releases depName=GoogleContainerTools/skaffold
skaffold: "2.13.2"
# renovate: datasource=github-releases depName=go-delve/delve
dlv: "1.24.0"
# renovate: datasource=github-releases depName=gotestyourself/gotestsum
gotestsum: "1.12.0"
# renovate: datasource=github-releases depName=elastic/crd-ref-docs
crd-ref-docs: "0.1.0"
# renovate: datasource=github-releases depName=vektra/mockery
mockery: "2.51.0"
# renovate: datasource=github-releases depName=kubernetes-sigs/controller-runtime
setup-envtest: "0.20.0"
# renovate: datasource=github-releases depName=rhysd/actionlint
actionlint: "1.7.7"
# renovate: datasource=github-releases depName=koalaman/shellcheck
shellcheck: "0.10.0"
