code-generator: "0.29.1"
controller-tools: "0.14.0"
kustomize: "5.3.0"
golangci-lint: "1.56.1"
skaffold: "2.3.1"
dlv: "1.22.0"
operator-sdk: "1.23.0"
yq: "4.34.1"
gotestsum: "1.11.0"
crd-ref-docs: "0.0.11"
