# renovate: datasource=github-tags depName=kubernetes/code-generator
code-generator: "0.30.3"
# renovate: datasource=github-releases depName=kubernetes-sigs/controller-tools
controller-tools: "0.15.0"
# renovate: datasource=github-releases depName=kubernetes-sigs/kustomize
kustomize: "5.4.3"
# renovate: datasource=github-releases depName=golangci/golangci-lint
golangci-lint: "1.60.1"
# renovate: datasource=github-releases depName=GoogleContainerTools/skaffold
skaffold: "2.13.1"
# renovate: datasource=github-releases depName=go-delve/delve
dlv: "1.23.0"
# renovate: datasource=github-releases depName=gotestyourself/gotestsum
gotestsum: "1.12.0"
# renovate: datasource=github-releases depName=elastic/crd-ref-docs
crd-ref-docs: "0.1.0"
