apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.konghq.com/v1alpha1",
          "kind": "ControlPlane",
          "metadata": {
            "name": "kong-controlplane-sample",
            "namespace": "kong"
          },
          "spec": {
            "containerImage": "kong/kubernetes-ingress-controller",
            "env": [
              {
                "name": "CONTROLLER_KONG_ADMIN_URL",
                "value": "https://kong-gateway-sample.kong.svc:8444"
              },
              {
                "name": "CONTROLLER_KONG_ADMIN_TLS_SKIP_VERIFY",
                "value": "true"
              },
              {
                "name": "CONTROLLER_PUBLISH_SERVICE",
                "value": "kong/kong-gateway-sample"
              },
              {
                "name": "POD_NAME",
                "valueFrom": {
                  "fieldRef": {
                    "apiVersion": "v1",
                    "fieldPath": "metadata.name"
                  }
                }
              },
              {
                "name": "CONTROLLER_FEATURE_GATES",
                "value": "Gateway=true"
              },
              {
                "name": "POD_NAMESPACE",
                "valueFrom": {
                  "fieldRef": {
                    "apiVersion": "v1",
                    "fieldPath": "metadata.namespace"
                  }
                }
              }
            ],
            "gatewayClass": "kong-gatewayclass-sample",
            "version": "2.2.1"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.19.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ControlPlane is the Schema for the controlplanes API
      displayName: Control Plane
      kind: ControlPlane
      name: controlplanes.operator.konghq.com
      version: v1alpha1
    - description: GatewayConfiguration is the Schema for the gatewayconfigurations
        API
      displayName: Gateway Configuration
      kind: GatewayConfiguration
      name: gatewayconfigurations.operator.konghq.com
      version: v1alpha1
  description: Kong Operator for Kubernetes
  displayName: Kong
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - gateway.networking.k8s.io
          resources:
          - gatewayclasses
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - gateway.networking.k8s.io
          resources:
          - gatewayclasses/status
          verbs:
          - get
          - update
        - apiGroups:
          - gateway.networking.k8s.io
          resources:
          - gateways
          verbs:
          - get
          - list
          - update
          - watch
        - apiGroups:
          - gateway.networking.k8s.io
          resources:
          - gateways/status
          verbs:
          - get
          - update
        - apiGroups:
          - operator.konghq.com
          resources:
          - controlplanes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operator.konghq.com
          resources:
          - controlplanes/finalizers
          verbs:
          - update
        - apiGroups:
          - operator.konghq.com
          resources:
          - controlplanes/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: operator-controller-manager
      deployments:
      - label:
          control-plane: controller-manager
        name: operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: controller:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - networking
  - gateway
  - ingress
  - kong
  - kubernetes
  - go
  links:
  - name: Operator
    url: https://operator.domain
  maturity: alpha
  provider:
    name: Kong Inc.
    url: https://konghq.com
  version: 0.0.1
