language: go

notifications:
  email:
    on_failure: never
    on_success: never

cache:
  apt: true
  directories:
  - $GOPATH/pkg/mod

env:
- GO111MODULE=on

go:
  - "1.12"

go_import_path: github.com/kong/kubernetes-ingress-controller

before_script:
- go get golang.org/x/lint/golint

script:
- make verify-codegen
- make test-all
