---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - operator.konghq.com
  resources:
  - controlplanes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.konghq.com
  resources:
  - controlplanes/finalizers
  verbs:
  - update
- apiGroups:
  - operator.konghq.com
  resources:
  - controlplanes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.konghq.com
  resources:
  - dataplanes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.konghq.com
  resources:
  - dataplanes/finalizers
  verbs:
  - update
- apiGroups:
  - operator.konghq.com
  resources:
  - dataplanes/status
  verbs:
  - get
  - patch
  - update
