apiVersion: v1
kind: Namespace
metadata:
  name: kong
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kong-serviceaccount
  namespace: kong
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kong-leader-election
rules:
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - configmaps
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kong-ingress
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - configuration.konghq.com
  resources:
  - kongclusterplugins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configuration.konghq.com
  resources:
  - kongclusterplugins/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - configuration.konghq.com
  resources:
  - kongconsumers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configuration.konghq.com
  resources:
  - kongconsumers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - configuration.konghq.com
  resources:
  - kongingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configuration.konghq.com
  resources:
  - kongingresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - configuration.konghq.com
  resources:
  - kongplugins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configuration.konghq.com
  resources:
  - kongplugins/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - configuration.konghq.com
  resources:
  - tcpingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configuration.konghq.com
  resources:
  - tcpingresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - configuration.konghq.com
  resources:
  - udpingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configuration.konghq.com
  resources:
  - udpingresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses/status
  verbs:
  - get
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways/status
  verbs:
  - get
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes/status
  verbs:
  - get
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - referencepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - referencepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - referencepolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - tcproutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - tcproutes/status
  verbs:
  - get
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - tlsroutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - tlsroutes/status
  verbs:
  - get
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - udproutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - udproutes/status
  verbs:
  - get
  - update
- apiGroups:
  - networking.internal.knative.dev
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.internal.knative.dev
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kong-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kong-leader-election
subjects:
- kind: ServiceAccount
  name: kong-serviceaccount
  namespace: kong
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kong-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kong-ingress
subjects:
- kind: ServiceAccount
  name: kong-serviceaccount
  namespace: kong
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpbin
  name: httpbin
  namespace: kong
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: httpbin
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpbin
  name: httpbin
  namespace: kong
spec:
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - image: kennethreitz/httpbin
        name: httpbin
        ports:
        - containerPort: 80
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: kong-gateway-sample
  namespace: kong
spec:
  gatewayClassName: kong-gatewayclass-sample
  listeners:
  - name: http
    port: 80
    protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GatewayClass
metadata:
  name: kong-gatewayclass-sample
spec:
  controllerName: konghq.com/kic-gateway-controller
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    httpbin.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: kong
  name: httpbin-ingress
  namespace: kong
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: httpbin
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: gateway-operator.konghq.com/v1alpha1
kind: ControlPlane
metadata:
  name: kong-controlplane-sample
  namespace: kong
spec:
  containerImage: kong/kubernetes-ingress-controller
  env:
  - name: CONTROLLER_KONG_ADMIN_URL
    value: https://kong-gateway-sample.kong.svc:8444
  - name: CONTROLLER_KONG_ADMIN_TLS_SKIP_VERIFY
    value: "true"
  - name: CONTROLLER_PUBLISH_SERVICE
    value: kong/kong-gateway-sample
  - name: POD_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.name
  - name: CONTROLLER_FEATURE_GATES
    value: Gateway=true
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.namespace
  gatewayClass: kong-gatewayclass-sample
  version: 2.2.1
---
apiVersion: gateway-operator.konghq.com/v1alpha1
kind: GatewayConfiguration
metadata:
  name: kong-gateway-sample
  namespace: kong
spec:
  containerImage: kong/kong
  env:
  - name: KONG_ADMIN_ACCESS_LOG
    value: /dev/stdout
  - name: KONG_ADMIN_ERROR_LOG
    value: /dev/stderr
  - name: KONG_ADMIN_GUI_ACCESS_LOG
    value: /dev/stdout
  - name: KONG_ADMIN_GUI_ERROR_LOG
    value: /dev/stderr
  - name: KONG_ADMIN_LISTEN
    value: 0.0.0.0:8444 ssl
  - name: KONG_CLUSTER_LISTEN
    value: "off"
  - name: KONG_DATABASE
    value: "off"
  - name: KONG_LUA_PACKAGE_PATH
    value: /opt/?.lua;/opt/?/init.lua;;
  - name: KONG_NGINX_WORKER_PROCESSES
    value: "2"
  - name: KONG_PLUGINS
    value: bundled
  - name: KONG_PORTAL_API_ACCESS_LOG
    value: /dev/stdout
  - name: KONG_PORTAL_API_ERROR_LOG
    value: /dev/stderr
  - name: KONG_PORT_MAPS
    value: 80:8000, 443:8443
  - name: KONG_PROXY_ACCESS_LOG
    value: /dev/stdout
  - name: KONG_PROXY_ERROR_LOG
    value: /dev/stderr
  - name: KONG_PROXY_LISTEN
    value: 0.0.0.0:8000, 0.0.0.0:8443 http2 ssl
  - name: KONG_STATUS_LISTEN
    value: 0.0.0.0:8100
  version: 2.7.1
---
apiVersion: gateway-operator.konghq.com/v1alpha1
kind: GatewayConfiguration
metadata:
  name: kong-gateway-sample-2
  namespace: kong
spec:
  containerImage: kong/kong
  env:
  - name: KONG_ADMIN_ACCESS_LOG
    value: /dev/stdout
  - name: KONG_ADMIN_ERROR_LOG
    value: /dev/stderr
  - name: KONG_ADMIN_GUI_ACCESS_LOG
    value: /dev/stdout
  - name: KONG_ADMIN_GUI_ERROR_LOG
    value: /dev/stderr
  - name: KONG_ADMIN_LISTEN
    value: 0.0.0.0:8444 ssl
  - name: KONG_CLUSTER_LISTEN
    value: "off"
  - name: KONG_DATABASE
    value: "off"
  - name: KONG_LUA_PACKAGE_PATH
    value: /opt/?.lua;/opt/?/init.lua;;
  - name: KONG_NGINX_WORKER_PROCESSES
    value: "2"
  - name: KONG_PLUGINS
    value: bundled
  - name: KONG_PORTAL_API_ACCESS_LOG
    value: /dev/stdout
  - name: KONG_PORTAL_API_ERROR_LOG
    value: /dev/stderr
  - name: KONG_PORT_MAPS
    value: 80:8000, 443:8443
  - name: KONG_PROXY_ACCESS_LOG
    value: /dev/stdout
  - name: KONG_PROXY_ERROR_LOG
    value: /dev/stderr
  - name: KONG_PROXY_LISTEN
    value: 0.0.0.0:8000, 0.0.0.0:8443 http2 ssl
  - name: KONG_STATUS_LISTEN
    value: 0.0.0.0:8100
  version: 2.7.1
---
apiVersion: gateway-operator.konghq.com/v1alpha1
kind: GatewayConfiguration
metadata:
  name: kong-gateway-sample-3
  namespace: kong
spec:
  containerImage: kong/kong
  env:
  - name: KONG_ADMIN_ACCESS_LOG
    value: /dev/stdout
  - name: KONG_ADMIN_ERROR_LOG
    value: /dev/stderr
  - name: KONG_ADMIN_GUI_ACCESS_LOG
    value: /dev/stdout
  - name: KONG_ADMIN_GUI_ERROR_LOG
    value: /dev/stderr
  - name: KONG_ADMIN_LISTEN
    value: 0.0.0.0:8444 ssl
  - name: KONG_CLUSTER_LISTEN
    value: "off"
  - name: KONG_DATABASE
    value: "off"
  - name: KONG_LUA_PACKAGE_PATH
    value: /opt/?.lua;/opt/?/init.lua;;
  - name: KONG_NGINX_WORKER_PROCESSES
    value: "2"
  - name: KONG_PLUGINS
    value: bundled
  - name: KONG_PORTAL_API_ACCESS_LOG
    value: /dev/stdout
  - name: KONG_PORTAL_API_ERROR_LOG
    value: /dev/stderr
  - name: KONG_PORT_MAPS
    value: 80:8000, 443:8443
  - name: KONG_PROXY_ACCESS_LOG
    value: /dev/stdout
  - name: KONG_PROXY_ERROR_LOG
    value: /dev/stderr
  - name: KONG_PROXY_LISTEN
    value: 0.0.0.0:8000, 0.0.0.0:8443 http2 ssl
  - name: KONG_STATUS_LISTEN
    value: 0.0.0.0:8100
  version: 2.7.1
