/*
Copyright 2022 Kong Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kong/gateway-operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKonnectControlPlanes implements KonnectControlPlaneInterface
type FakeKonnectControlPlanes struct {
	Fake *FakeApisV1alpha1
	ns   string
}

var konnectcontrolplanesResource = v1alpha1.SchemeGroupVersion.WithResource("konnectcontrolplanes")

var konnectcontrolplanesKind = v1alpha1.SchemeGroupVersion.WithKind("KonnectControlPlane")

// Get takes name of the konnectControlPlane, and returns the corresponding konnectControlPlane object, and an error if there is any.
func (c *FakeKonnectControlPlanes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KonnectControlPlane, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(konnectcontrolplanesResource, c.ns, name), &v1alpha1.KonnectControlPlane{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KonnectControlPlane), err
}

// List takes label and field selectors, and returns the list of KonnectControlPlanes that match those selectors.
func (c *FakeKonnectControlPlanes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KonnectControlPlaneList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(konnectcontrolplanesResource, konnectcontrolplanesKind, c.ns, opts), &v1alpha1.KonnectControlPlaneList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KonnectControlPlaneList{ListMeta: obj.(*v1alpha1.KonnectControlPlaneList).ListMeta}
	for _, item := range obj.(*v1alpha1.KonnectControlPlaneList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested konnectControlPlanes.
func (c *FakeKonnectControlPlanes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(konnectcontrolplanesResource, c.ns, opts))

}

// Create takes the representation of a konnectControlPlane and creates it.  Returns the server's representation of the konnectControlPlane, and an error, if there is any.
func (c *FakeKonnectControlPlanes) Create(ctx context.Context, konnectControlPlane *v1alpha1.KonnectControlPlane, opts v1.CreateOptions) (result *v1alpha1.KonnectControlPlane, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(konnectcontrolplanesResource, c.ns, konnectControlPlane), &v1alpha1.KonnectControlPlane{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KonnectControlPlane), err
}

// Update takes the representation of a konnectControlPlane and updates it. Returns the server's representation of the konnectControlPlane, and an error, if there is any.
func (c *FakeKonnectControlPlanes) Update(ctx context.Context, konnectControlPlane *v1alpha1.KonnectControlPlane, opts v1.UpdateOptions) (result *v1alpha1.KonnectControlPlane, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(konnectcontrolplanesResource, c.ns, konnectControlPlane), &v1alpha1.KonnectControlPlane{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KonnectControlPlane), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKonnectControlPlanes) UpdateStatus(ctx context.Context, konnectControlPlane *v1alpha1.KonnectControlPlane, opts v1.UpdateOptions) (*v1alpha1.KonnectControlPlane, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(konnectcontrolplanesResource, "status", c.ns, konnectControlPlane), &v1alpha1.KonnectControlPlane{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KonnectControlPlane), err
}

// Delete takes name of the konnectControlPlane and deletes it. Returns an error if one occurs.
func (c *FakeKonnectControlPlanes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(konnectcontrolplanesResource, c.ns, name, opts), &v1alpha1.KonnectControlPlane{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKonnectControlPlanes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(konnectcontrolplanesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KonnectControlPlaneList{})
	return err
}

// Patch applies the patch and returns the patched konnectControlPlane.
func (c *FakeKonnectControlPlanes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KonnectControlPlane, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(konnectcontrolplanesResource, c.ns, name, pt, data, subresources...), &v1alpha1.KonnectControlPlane{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KonnectControlPlane), err
}
