/*
Copyright 2022 Kong Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kong/gateway-operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKonnectAPIAuthConfigurations implements KonnectAPIAuthConfigurationInterface
type FakeKonnectAPIAuthConfigurations struct {
	Fake *FakeApisV1alpha1
	ns   string
}

var konnectapiauthconfigurationsResource = v1alpha1.SchemeGroupVersion.WithResource("konnectapiauthconfigurations")

var konnectapiauthconfigurationsKind = v1alpha1.SchemeGroupVersion.WithKind("KonnectAPIAuthConfiguration")

// Get takes name of the konnectAPIAuthConfiguration, and returns the corresponding konnectAPIAuthConfiguration object, and an error if there is any.
func (c *FakeKonnectAPIAuthConfigurations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KonnectAPIAuthConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(konnectapiauthconfigurationsResource, c.ns, name), &v1alpha1.KonnectAPIAuthConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KonnectAPIAuthConfiguration), err
}

// List takes label and field selectors, and returns the list of KonnectAPIAuthConfigurations that match those selectors.
func (c *FakeKonnectAPIAuthConfigurations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KonnectAPIAuthConfigurationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(konnectapiauthconfigurationsResource, konnectapiauthconfigurationsKind, c.ns, opts), &v1alpha1.KonnectAPIAuthConfigurationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KonnectAPIAuthConfigurationList{ListMeta: obj.(*v1alpha1.KonnectAPIAuthConfigurationList).ListMeta}
	for _, item := range obj.(*v1alpha1.KonnectAPIAuthConfigurationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested konnectAPIAuthConfigurations.
func (c *FakeKonnectAPIAuthConfigurations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(konnectapiauthconfigurationsResource, c.ns, opts))

}

// Create takes the representation of a konnectAPIAuthConfiguration and creates it.  Returns the server's representation of the konnectAPIAuthConfiguration, and an error, if there is any.
func (c *FakeKonnectAPIAuthConfigurations) Create(ctx context.Context, konnectAPIAuthConfiguration *v1alpha1.KonnectAPIAuthConfiguration, opts v1.CreateOptions) (result *v1alpha1.KonnectAPIAuthConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(konnectapiauthconfigurationsResource, c.ns, konnectAPIAuthConfiguration), &v1alpha1.KonnectAPIAuthConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KonnectAPIAuthConfiguration), err
}

// Update takes the representation of a konnectAPIAuthConfiguration and updates it. Returns the server's representation of the konnectAPIAuthConfiguration, and an error, if there is any.
func (c *FakeKonnectAPIAuthConfigurations) Update(ctx context.Context, konnectAPIAuthConfiguration *v1alpha1.KonnectAPIAuthConfiguration, opts v1.UpdateOptions) (result *v1alpha1.KonnectAPIAuthConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(konnectapiauthconfigurationsResource, c.ns, konnectAPIAuthConfiguration), &v1alpha1.KonnectAPIAuthConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KonnectAPIAuthConfiguration), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKonnectAPIAuthConfigurations) UpdateStatus(ctx context.Context, konnectAPIAuthConfiguration *v1alpha1.KonnectAPIAuthConfiguration, opts v1.UpdateOptions) (*v1alpha1.KonnectAPIAuthConfiguration, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(konnectapiauthconfigurationsResource, "status", c.ns, konnectAPIAuthConfiguration), &v1alpha1.KonnectAPIAuthConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KonnectAPIAuthConfiguration), err
}

// Delete takes name of the konnectAPIAuthConfiguration and deletes it. Returns an error if one occurs.
func (c *FakeKonnectAPIAuthConfigurations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(konnectapiauthconfigurationsResource, c.ns, name, opts), &v1alpha1.KonnectAPIAuthConfiguration{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKonnectAPIAuthConfigurations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(konnectapiauthconfigurationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KonnectAPIAuthConfigurationList{})
	return err
}

// Patch applies the patch and returns the patched konnectAPIAuthConfiguration.
func (c *FakeKonnectAPIAuthConfigurations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KonnectAPIAuthConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(konnectapiauthconfigurationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.KonnectAPIAuthConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KonnectAPIAuthConfiguration), err
}
