apiVersion: operator.konghq.com/v1alpha1
kind: ControlPlane
metadata:
  name: kong-controlplane-sample
  namespace: kong
spec:
  gatewayClass: kong-gatewayclass-sample
  containerImage: kong/kubernetes-ingress-controller
  version: 2.2.1
  env:
  - name: CONTROLLER_KONG_ADMIN_URL
    value: "https://kong-gateway-sample.kong.svc:8444"
  - name: CONTROLLER_KONG_ADMIN_TLS_SKIP_VERIFY
    value: "true"
  - name: CONTROLLER_PUBLISH_SERVICE
    value: "kong/kong-gateway-sample"
  - name: POD_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.name
  - name: CONTROLLER_FEATURE_GATES
    value: "Gateway=true"
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.namespace

