# This example will create a ControlPlane and a DataPlane configured by the ControlPlane with KonnectExtension attached
# to them. It means that both ControlPlane and DataPlane will communicate with Konnect Control Plane specified in the
# KonnectExtension spec.
#
# Ensure that you create a secret containing your cluster certificate before applying this
# kubectl create secret tls konnect-client-tls -n kong --cert=./tls.crt --key=./tls.key
# apiVersion: v1
# kind: Secret
# metadata:
#   name: konnect-client-tls
# type: kubernetes.io/tls
# stringData:
#   tls.crt: |
#     -----BEGIN CERTIFICATE-----
#     ...
#     -----END CERTIFICATE-----
#   tls.key: |
#     -----BEGIN PRIVATE KEY-----
#     ...
#     -----END PRIVATE KEY-----
---
kind: KonnectAPIAuthConfiguration
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: konnect-api-auth-dev-1
  namespace: default
spec:
  type: token
  token: kpat_XXXXXXXXX
  serverURL: us.api.konghq.com
---
kind: KonnectExtension
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: my-konnect-config
  namespace: default
  annotations:
    konghq.com/override: "true"
spec:
  konnectControlPlane:
    controlPlaneRef:
      type: konnectID
      konnectID: c846c30c-77da-40e6-b0c8-66ed7e16c497
  dataPlaneClientAuth:
    certificateSecret:
      provisioning: Manual
      secretRef:
        name: konnect-client-tls
  konnect:
    authRef:
      name: konnect-api-auth-dev-1
---
apiVersion: gateway-operator.konghq.com/v1beta1
kind: ControlPlane
metadata:
  name: controlplane-example
spec:
  extensions:
    - kind: KonnectExtension
      name: my-konnect-config
      group: konnect.konghq.com
  dataplane: konnect-extension-example
  gatewayClass: kong
  deployment:
    podTemplateSpec:
      metadata:
        labels:
          controlplane-pod-label: example
      spec:
        containers:
        - name: controller
          # renovate: datasource=docker versioning=docker
          image: kong/kubernetes-ingress-controller:3.4.3
          readinessProbe:
            initialDelaySeconds: 1
            periodSeconds: 3
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
---
apiVersion: gateway-operator.konghq.com/v1beta1
kind: DataPlane
metadata:
  name: konnect-extension-example
spec:
  extensions:
    - kind: KonnectExtension
      name: my-konnect-config
      group: konnect.konghq.com
  deployment:
    replicas: 3
    podTemplateSpec:
      metadata:
        labels:
          dataplane-pod-label: example
        annotations:
          dataplane-pod-annotation: example
      spec:
        containers:
          - name: proxy
            # renovate: datasource=docker versioning=docker
            image: kong/kong-gateway:3.9
            readinessProbe:
              initialDelaySeconds: 1
              periodSeconds: 1
