apiVersion: gateway-operator.konghq.com/v1alpha1
kind: DataPlaneMetricsExtension
metadata:
  name: dp-metrics-example
spec:
  serviceSelector:
    matchNames:
      - name: example-service
  config:
    latency: true
    bandwidth: true
    upstreamHealth: true
    statusCode: true
