kind: KonnectAPIAuthConfiguration
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: konnect-api-auth-dev-1
  namespace: default
spec:
  type: token
  token: kpat_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  serverURL: us.api.konghq.com
---
kind: KonnectGatewayControlPlane
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: test-cp-acl
  namespace: default
spec:
  name: test-cp-acl
  labels:
    app: test-cp-acl
    key1: test-cp-acl
  konnect:
    authRef:
      name: konnect-api-auth-dev-1
---
kind: KongConsumer
apiVersion: configuration.konghq.com/v1
metadata:
  name: consumer-acl-1
  namespace: default
username: consumer1
spec:
  controlPlaneRef:
    type: konnectNamespacedRef
    konnectNamespacedRef:
      name: test-cp-acl
---
apiVersion: configuration.konghq.com/v1alpha1
kind: KongCredentialACL
metadata:
  name: acl-1
  namespace: default
spec:
  consumerRef:
    name: consumer-acl-1
  group: group1
