---
kind: KonnectGatewayControlPlane
apiVersion: konnect.konghq.com/v1alpha2
metadata:
  name: test
spec:
  source: Mirror
  mirror:
    konnect:
      id: 03b496a0-a38a-4370-8e50-9a9e71cef6df
  konnect:
    authRef:
      name: konnect-api-auth-dev
---
kind: KonnectAPIAuthConfiguration
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: konnect-api-auth-dev
spec:
  type: token
  token: kpat_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  serverURL: us.api.konghq.tech
