kind: KonnectAPIAuthConfiguration
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: konnect-api-auth-dev-1
  namespace: default
spec:
  type: token
  token: kpat_XXXXXXXXXXXXXXXXXXX
  serverURL: us.api.konghq.tech
---
kind: KonnectGatewayControlPlane
apiVersion: konnect.konghq.com/v1alpha2
metadata:
  name: test1
  namespace: default
spec:
  createControlPlaneRequest:
    name: test1
  konnect:
    authRef:
      name: konnect-api-auth-dev-1
---
kind: KonnectGatewayControlPlane
apiVersion: konnect.konghq.com/v1alpha2
metadata:
  name: test2
  namespace: default
spec:
  createControlPlaneRequest:
    name: test2
  konnect:
    authRef:
      name: konnect-api-auth-dev-1
---
kind: KonnectGatewayControlPlane
apiVersion: konnect.konghq.com/v1alpha2
metadata:
  name: test3
  namespace: default
spec:
  createControlPlaneRequest:
    name: test3
  konnect:
    authRef:
      name: konnect-api-auth-dev-1
---
kind: KonnectGatewayControlPlane
apiVersion: konnect.konghq.com/v1alpha2
metadata:
  name: group1
  namespace: default
spec:
  createControlPlaneRequest:
    name: group1
    cluster_type: CLUSTER_TYPE_CONTROL_PLANE_GROUP
    labels:
      app: group1
      key1: group1
  members:
  - name: test1
  - name: test2
  - name: test3
  konnect:
    authRef:
      name: konnect-api-auth-dev-1
