kind: KonnectAPIAuthConfiguration
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: konnect-api-auth-dev-1
  namespace: default
spec:
  type: token
  token: kpat_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  serverURL: us.api.konghq.com
---
kind: KonnectGatewayControlPlane
apiVersion: konnect.konghq.com/v1alpha2
metadata:
  name: test-cp-acl-auth
  namespace: default
spec:
  createControlPlaneRequest:
    name: test-cp-acl-auth
    labels:
      app: test-cp-acl-auth
      key1: test-cp-acl-auth
  konnect:
    authRef:
      name: konnect-api-auth-dev-1
---
kind: KongConsumer
apiVersion: configuration.konghq.com/v1
metadata:
  name: consumer1
  namespace: default
username: consumer1
spec:
  controlPlaneRef:
    type: konnectNamespacedRef
    konnectNamespacedRef:
      name: test-cp-acl-auth
credentials:
- consumer1-acl-1
---
kind: Secret
apiVersion: v1
metadata:
  name: consumer1-acl-1
  namespace: default
  labels:
    konghq.com/credential: acl
stringData:
  group: "acl-group"
