---
kind: KonnectAPIAuthConfiguration
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: demo-auth
  namespace: default
spec:
  type: token
  token: kpat_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  serverURL: us.api.konghq.tech
---
kind: KonnectGatewayControlPlane
apiVersion: konnect.konghq.com/v1alpha2
metadata:
  name: demo-cp
  namespace: default
spec:
  createControlPlaneRequest:
    name: demo-cp
    labels:
      app: demo-cp
      key1: demo-cp
  konnect:
    authRef:
      name: demo-auth
      # namespace not required if APIAuthConfiguration is in the same namespace
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
 name: rate-limit-5-min
config:
 minute: 5
 policy: local
plugin: rate-limiting
---
apiVersion: configuration.konghq.com/v1alpha1
kind: KongPluginBinding
metadata:
  name: global-plugin-binding
spec:
  scope: GlobalInControlPlane
  controlPlaneRef:
    type: konnectNamespacedRef
    konnectNamespacedRef:
      name: demo-cp
  pluginRef:
    name: rate-limit-5-min
