## Append samples you want in your CSV to this file as resources ##
resources:
- operator_v1alpha1_controlplane.yaml
- operator_v1alpha1_dataplane.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
