## Append samples you want in your CSV to this file as resources ##
resources:
- httpbin.yaml
- control_plane.yaml
- gateway-configs.yaml
- gateway.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
