# You can test this sample with a KTF env:
#
# - ktf envs create --addon metallb
# - kubectl kustomize https://github.com/Kong/kubernetes-ingress-controller/config/crd | kubectl apply -f -
# - kubectl kustomize https://github.com/kubernetes-sigs/gateway-api/config/crd | kubectl apply -f -
# - kubectl kustomize https://github.com/Kong/kubernetes-ingress-controller/config/rbac | kubectl apply -f -
# - kubectl kustomize config/crd | kubectl apply -f -
# - make install run
#
# For other environments, the kustomize apply commands need to be run.
apiVersion: operator.konghq.com/v1alpha1
kind: ControlPlane
metadata:
  name: kong-controlplane-sample
  namespace: kong
spec:
  gatewayClass: kong-gatewayclass-sample
  containerImage: kong/kubernetes-ingress-controller
  version: 2.2.1
  env:
  - name: CONTROLLER_KONG_ADMIN_URL
    value: "https://kong-gateway-sample.kong.svc:8444"
  - name: CONTROLLER_KONG_ADMIN_TLS_SKIP_VERIFY
    value: "true"
  - name: CONTROLLER_PUBLISH_SERVICE
    value: "kong/kong-gateway-sample"
  - name: POD_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.name
  - name: CONTROLLER_FEATURE_GATES
    value: "Gateway=true"
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.namespace

