image:
  repository: docker.io/kong/nightly-kong-operator
  tag: "20250409"
  effectiveSemver: "2.0.0-alpha.0"

livenessProbe:
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 1
  periodSeconds: 1

readinessProbe:
  initialDelaySeconds: 1
  periodSeconds: 1

env:
  anonymous_reports: "false"
