{{- define "gvList" -}}
{{- $groupVersions := . -}}

<!-- This document is generated by KGO's 'generate.docs' make target, DO NOT EDIT -->

{{- /* Prepare a GV -> shouldIncludePackage mapping for later lookups */ -}}
{{- $shouldIncludePackageByGV := dict -}}
{{- range $groupVersions -}}
    {{- $hasAtLeastOneTypeWithInclude := false -}}
    {{- $hasIncludeAllTypes := index .Markers "apireference:kgo:include-all-types" -}}
    {{- range $typ := .SortedTypes -}}
        {{- if index $typ.Markers "apireference:kgo:include" -}}
            {{- $hasAtLeastOneTypeWithInclude = true -}}
        {{- end -}}
    {{- end -}}
    {{- if or $hasAtLeastOneTypeWithInclude $hasIncludeAllTypes -}}
        {{- $_ := set $shouldIncludePackageByGV .GroupVersionString true -}}
    {{- end -}}
{{- end }}

## Debug

{{- range $groupVersions }}
- {{ .GroupVersionString }}
    - Kinds: {{ len .Kinds }}
    - Types: {{ len .Types }}
    - Markers: {{ .Markers }}
    - Should Include: {{ hasKey $shouldIncludePackageByGV .GroupVersionString }}
{{- end }}

## Packages
{{- range $groupVersions }}
{{- if hasKey $shouldIncludePackageByGV .GroupVersionString }}
- {{ markdownRenderGVLink . }}
{{- end }}
{{- end }}

{{ range $groupVersions }}
{{- if hasKey $shouldIncludePackageByGV .GroupVersionString }}
{{ template "gvDetails" . }}
{{- end }}
{{ end }}

{{- end -}}
