/*
Copyright 2022 Kong Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kong/gateway-operator/api/v1alpha1"
	scheme "github.com/kong/gateway-operator/pkg/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KonnectAPIAuthConfigurationsGetter has a method to return a KonnectAPIAuthConfigurationInterface.
// A group's client should implement this interface.
type KonnectAPIAuthConfigurationsGetter interface {
	KonnectAPIAuthConfigurations(namespace string) KonnectAPIAuthConfigurationInterface
}

// KonnectAPIAuthConfigurationInterface has methods to work with KonnectAPIAuthConfiguration resources.
type KonnectAPIAuthConfigurationInterface interface {
	Create(ctx context.Context, konnectAPIAuthConfiguration *v1alpha1.KonnectAPIAuthConfiguration, opts v1.CreateOptions) (*v1alpha1.KonnectAPIAuthConfiguration, error)
	Update(ctx context.Context, konnectAPIAuthConfiguration *v1alpha1.KonnectAPIAuthConfiguration, opts v1.UpdateOptions) (*v1alpha1.KonnectAPIAuthConfiguration, error)
	UpdateStatus(ctx context.Context, konnectAPIAuthConfiguration *v1alpha1.KonnectAPIAuthConfiguration, opts v1.UpdateOptions) (*v1alpha1.KonnectAPIAuthConfiguration, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.KonnectAPIAuthConfiguration, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.KonnectAPIAuthConfigurationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KonnectAPIAuthConfiguration, err error)
	KonnectAPIAuthConfigurationExpansion
}

// konnectAPIAuthConfigurations implements KonnectAPIAuthConfigurationInterface
type konnectAPIAuthConfigurations struct {
	client rest.Interface
	ns     string
}

// newKonnectAPIAuthConfigurations returns a KonnectAPIAuthConfigurations
func newKonnectAPIAuthConfigurations(c *ApisV1alpha1Client, namespace string) *konnectAPIAuthConfigurations {
	return &konnectAPIAuthConfigurations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the konnectAPIAuthConfiguration, and returns the corresponding konnectAPIAuthConfiguration object, and an error if there is any.
func (c *konnectAPIAuthConfigurations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KonnectAPIAuthConfiguration, err error) {
	result = &v1alpha1.KonnectAPIAuthConfiguration{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("konnectapiauthconfigurations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KonnectAPIAuthConfigurations that match those selectors.
func (c *konnectAPIAuthConfigurations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KonnectAPIAuthConfigurationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.KonnectAPIAuthConfigurationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("konnectapiauthconfigurations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested konnectAPIAuthConfigurations.
func (c *konnectAPIAuthConfigurations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("konnectapiauthconfigurations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a konnectAPIAuthConfiguration and creates it.  Returns the server's representation of the konnectAPIAuthConfiguration, and an error, if there is any.
func (c *konnectAPIAuthConfigurations) Create(ctx context.Context, konnectAPIAuthConfiguration *v1alpha1.KonnectAPIAuthConfiguration, opts v1.CreateOptions) (result *v1alpha1.KonnectAPIAuthConfiguration, err error) {
	result = &v1alpha1.KonnectAPIAuthConfiguration{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("konnectapiauthconfigurations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(konnectAPIAuthConfiguration).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a konnectAPIAuthConfiguration and updates it. Returns the server's representation of the konnectAPIAuthConfiguration, and an error, if there is any.
func (c *konnectAPIAuthConfigurations) Update(ctx context.Context, konnectAPIAuthConfiguration *v1alpha1.KonnectAPIAuthConfiguration, opts v1.UpdateOptions) (result *v1alpha1.KonnectAPIAuthConfiguration, err error) {
	result = &v1alpha1.KonnectAPIAuthConfiguration{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("konnectapiauthconfigurations").
		Name(konnectAPIAuthConfiguration.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(konnectAPIAuthConfiguration).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *konnectAPIAuthConfigurations) UpdateStatus(ctx context.Context, konnectAPIAuthConfiguration *v1alpha1.KonnectAPIAuthConfiguration, opts v1.UpdateOptions) (result *v1alpha1.KonnectAPIAuthConfiguration, err error) {
	result = &v1alpha1.KonnectAPIAuthConfiguration{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("konnectapiauthconfigurations").
		Name(konnectAPIAuthConfiguration.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(konnectAPIAuthConfiguration).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the konnectAPIAuthConfiguration and deletes it. Returns an error if one occurs.
func (c *konnectAPIAuthConfigurations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("konnectapiauthconfigurations").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *konnectAPIAuthConfigurations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("konnectapiauthconfigurations").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched konnectAPIAuthConfiguration.
func (c *konnectAPIAuthConfigurations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KonnectAPIAuthConfiguration, err error) {
	result = &v1alpha1.KonnectAPIAuthConfiguration{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("konnectapiauthconfigurations").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
