name: Reusable govulncheck

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git reference to check out'
        required: true
        type: string

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit
    - name: Checkout repository
      id: checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: ${{ inputs.ref }}
        
    - uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
      with:
        repo-checkout: false
        output-format: sarif
        output-file: results_${{ steps.checkout.outputs.commit }}.sarif

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@51f77329afa6477de8c49fc9c7046c15b9a4e79d # v3.29.5
      with:
        sarif_file: results_${{ steps.checkout.outputs.commit }}.sarif
        ref: refs/heads/${{ inputs.ref }}
        sha: ${{ steps.checkout.outputs.commit }}
        category: govulncheck
