name: Reusable govulncheck

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git reference to check out'
        required: true
        type: string

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - name: Checkout repository
      id: checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: ${{ inputs.ref }}
        
    - uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
      with:
        repo-checkout: false
        output-format: sarif
        output-file: results_${{ steps.checkout.outputs.commit }}.sarif

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@ff0a06e83cb2de871e5a09832bc6a81e7276941f # v3.28.18
      with:
        sarif_file: results_${{ steps.checkout.outputs.commit }}.sarif
        ref: refs/heads/${{ inputs.ref }}
        sha: ${{ steps.checkout.outputs.commit }}
        category: govulncheck
