name: Build container image
# This run-name will contain the branch name when run with pull_request or
# pull_request_target event.
# Otherwise it will contain the tag name if present or SHA.
run-name: Build container image ${{ github.head_ref || ( github.ref_type == 'tag' && github.ref_name || github.sha ) }}

concurrency:
  # Run only for most recent commit in PRs but for all tags and commits on main
  # Ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || ( github.ref_type == 'tag' && github.ref_name || github.sha ) }}
  cancel-in-progress: true

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
      - '*'
  workflow_dispatch: {}

jobs:
  build:
    uses: ./.github/workflows/__build-workflow.yaml
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_PUSH_TOKEN }}
      gh-pat: ${{ secrets.PAT_GITHUB }}
    with:
      username: ${{ vars.DOCKERHUB_PUSH_USERNAME }}
      registry: docker.io
      image-name: ${{ vars.DOCKERHUB_IMAGE_NAME }}
      # If we pushed then it means we want to build and push the image.
      # Branch filter above will decide pushes to which branch will trigger this.
      push: ${{ github.event.action == 'push' }}
