name: Sync charts to charts repo

concurrency:
  # Run only for most recent commit in PRs but for all tags and commits on main
  # Ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || ( github.ref_type == 'tag' && github.ref_name || github.sha ) }}
  cancel-in-progress: true

on:
  push:
    paths:
      - charts/**
      - .github/charts-sync.yaml
      - .github/workflows/charts-sync.yaml
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: BetaHuhn/repo-file-sync-action@8b92be3375cf1d1b0cd579af488a9255572e4619 # v1.21.1
        with:
          GH_PAT: ${{ secrets.PAT_GITHUB }}
          CONFIG_PATH: .github/charts-sync.yaml
          TEAM_REVIEWERS: Kong/k8s-maintainers
          OVERWRITE_EXISTING_PR: true
          PR_BODY: |
            ### Sync charts from ${{ github.repository }}

            This PR was automatically generated by the `sync-charts` workflow.
            It syncs the charts/ directory from the ${{ github.repository }} repository.
