name: govulncheck schedule

concurrency:
  # Run only for most recent commit in PRs but for all tags and commits on main
  # Ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '42 1 * * *'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  analyze:
    uses: ./.github/workflows/__govulncheck.yaml
    strategy:
      fail-fast: false
      matrix:
        branch:
        - main
        - release/1.4.x
    with:
      ref: ${{ matrix.branch }}
    permissions:
      security-events: write
      contents: read
