name: govulncheck
run-name: govulncheck ${{ github.head_ref }}

concurrency:
  # Run only for most recent commit in PRs but for all tags and commits on main
  # Ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - release/*
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'
      - 'SECURITY.md'
      - 'LICENSE'
      - 'LICENSES'
      - '.github/ISSUE_TEMPLATE/**'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  analyze:
    uses: ./.github/workflows/__govulncheck.yaml
    with:
      ref: ${{ github.ref_name }}
    permissions:
      security-events: write
      contents: read
