name: nightly

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build-push-images:
    uses: ./.github/workflows/__build-workflow.yaml
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_PUSH_TOKEN }}
      gh-pat: ${{ secrets.PAT_GITHUB }}
    with:
      username: ${{ vars.DOCKERHUB_PUSH_USERNAME }}
      registry: docker.io
      image-name: ${{ vars.DOCKERHUB_IMAGE_NAME_NIGHTLY }}
      push: true
