name: nightly

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch: {}

permissions:
  contents: read
  actions: read

jobs:
  build-push-images:
    uses: ./.github/workflows/__build-workflow.yaml
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_PUSH_TOKEN_NIGHTLY }}
      gh-pat: ${{ secrets.PAT_GITHUB }}
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
      slack-team-id: ${{ secrets.SLACK_TEAM_ID }}
    with:
      username: ${{ vars.DOCKERHUB_PUSH_USERNAME_NIGHTLY }}
      registry: docker.io
      image-name: ${{ vars.DOCKERHUB_IMAGE_NAME_NIGHTLY }}
      push: true
      slack-send: true
