name: release
run-name: "Release ${{ format('{0} (type: {1}) (branch: {2})', inputs.tag, inputs.release-type, inputs.base) }} "

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The version to release (e.g. v1.2.3)
        required: true
      base:
        description: The base branch from which to release and against which to create a release PR.
        type: string
        default: 'main'
        required: false
      latest:
        description: Whether to tag this build latest
        type: boolean
        default: false
      release_type:
        description: Whether to make a created release a pre-release
        required: true
        default: 'prerelease'
        type: choice
        options:
        - prerelease
        - release

jobs:
  release:
    uses: ./.github/workflows/__release-workflow.yaml
    secrets:
      dockerhub-push-token: ${{ secrets.DOCKERHUB_PUSH_TOKEN }}
      gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      gh-pat: ${{ secrets.PAT_GITHUB }}
    with:
      dockerhub-push-username: ${{ vars.DOCKERHUB_PUSH_USERNAME  }}
      image-name: ${{ vars.DOCKERHUB_IMAGE_NAME }}
      latest: ${{ inputs.latest }}
      tag: ${{ inputs.tag }}
      base: ${{ inputs.base }}
      release-type: ${{ inputs.release_type }}
      regenerate-manifests: true
